apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-sky-setting
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          name: copyright
          label: 版权信息
          value: "2020 - 2024 Halo Theme "
          help: "页脚版权信息 (示例：2020 - 2024 Halo Theme)"
        - $formkit: group
          name: icp_police
          label: 备案信息
          children:
            - $formkit: text
              name: icp
              label: ICP 备案号
              value: ""
              help: "ICP 备案信息将展示在页脚中，不填不展示（示例：京ICP备00000000号-1）"
            - $formkit: text
              name: icp_link
              label: ICP备案跳转链接
              value: https://beian.miit.gov.cn/
            - $formkit: text
              name: police
              label: 公网安备号
              value: ""
              help: "公网安备信息将展示在页脚中，不填不展示，（示例：京公网安备00000000号）"
            - $formkit: text
              name: police_link
              label: 公安联网备案跳转链接
              value: https://beian.mps.gov.cn/#/query/webSearch
    
    - group: style
      label: 样式
      formSchema:
        - $formkit: radio
          name: color_scheme
          label: 默认配色
          value: system
          options:
            - label: 跟随系统
              value: system
            - label: 深色
              value: dark
            - label: 浅色
              value: light
        - $formkit: color
          name: background_color
          label: 背景颜色
          value: "#f2f2f2"

    - group: layout
      label: 布局
      formSchema:
        - $formkit: radio
          name: nav
          label: 导航栏布局
          value: "single"
          options: 
            - label: 单栏
              value: "single"
            - label: 双栏
              value: "double"