apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-Sky
spec:
  displayName: Sky
  author:
    name:  ltacit
    website: "https://halo.run"
  description: 本地测试主题
  logo: "https://cdn.jsdelivr.net/gh/QiYuSky/zone-pic@main/icon202404162231981.png"
  website: "https://github.com/QiYuSky/Halo-Theme-Sky"
  repo: "https://github.com/QiYuSky/Halo-Theme-Sky.git"
  settingName: "theme-Sky-setting"
  configMapName: "theme-Sky-configMap"
  version: "0.1.0"
  requires: ">=2.13.0"

